### ISSUE TITLE
求教lua的使用

### ISSUE THREAD

**Issue by wwzrh** [fxliang/weasel_config#2]
想使用lua输入大写金额，如323.5元=叁佰贰拾叁元伍角（lua脚本能否实现吗？）
；
在terra_pinyin.schema.yaml中engine/translators/加了：
添加 - lua_translator@number_translator
；
在rime.lua加了：
添加  number_translator = require("number")
；
保证了lua\number.lua文件夹的脚本文件（本weasel_config项目的）
；
打"/dx323.5"无法用，怎样打出大写金额？
@fxliang

**Comment by fxliang** [comment]
https://github.com/fxliang/weasel_config/blob/main/base.yaml#L26

因为你没有对应修改类似的设定位置

**Comment by wwzrh** [comment]
[terra_pinyin.schema.yaml.txt](https://github.com/fxliang/weasel_config/files/11645289/terra_pinyin.schema.yaml.txt)

**Comment by wwzrh** [comment]
[terra_pinyin.schema.yaml.txt](https://github.com/fxliang/weasel_config/files/11645291/terra_pinyin.schema.yaml.txt)

不行呢, 帮忙看看代码

另外是不是/dx打头?

**Comment by fxliang** [comment]
所有你改的和我不一样的地方，自行检查吧。你改的必然是你理解了的，不然应该直接抄着用。

**Comment by fxliang** [comment]
还没有发现问题？你translator的名字打错了

**Comment by wwzrh** [comment]
多谢
